version: '3.0'
services:
  API_CONTAINER_NAME:
    container_name: API_CONTAINER_NAME
    build: .
    image: solenya_express_api
    user: node
    working_dir: /home/node/app
    labels:
      traefik.frontend.rule: "Host:TRAEFIK_ENV.chas.school"
    volumes:
      - ./:/home/node/app
    environment:
      - POSTGRES_HOST=DB_CONTAINER_NAME
    depends_on:
      - DB_CONTAINER_NAME
    env_file:
      - .env
  DB_CONTAINER_NAME:
    container_name: DB_CONTAINER_NAME
    image: onjin/alpine-postgres:9.6
    volumes:
      - DB_CONTAINER_NAME:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  DB_CONTAINER_NAME:
